sudo: false
language: python

python:
- 2.6
- 2.7
- 3.4

before_install:
  # System Info
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  
    # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n blosc_env python=$TRAVIS_PYTHON_VERSION numpy nose
  - source activate blosc_env
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then conda install unittest2; fi

install:
  - pip install .
script:
  - mkdir empty
  - cd empty
  - python -c"import blosc; blosc.print_versions()"
  - nosetests --with-doctest blosc

notifications:
  email: false

